#!/usr/bin/env python3
"""
Multi-Criteria Prototype Ranking via Global Cost.

USAGE GUIDELINES
----------------
Dependencies:
    - python 3.7+
    - pandas
    - numpy
    Install via: pip install pandas numpy

Input:
    Requires BOTH metrics tables generated by earlier scripts:
    1. <landmarks_root>/metrics/place_metrics_combined.csv
    2. <landmarks_root>/metrics/posture_features_combined.csv

Execution:
    python 09_rank_prototypes.py --landmarks-root A:\Automated_chain_BETA\Participant_Landmarks

Outputs:
    1. Prints the top 3 prototypes per height to the console.
    2. Saves the full ranked list to:
       <landmarks_root>/metrics/prototype_rankings_by_height.csv

Design Notes:
    This script standardizes distinct cost metrics (like seconds, mm, and REBA points)
    into Z-scores, creating a 'Global Cost' variable. Lower is assumed to be better.
    If you need to switch task-hands, change `reba_grand_right` to `reba_grand_left`
    in the COST_METRICS list below.
"""

import argparse
import sys
from pathlib import Path
import pandas as pd
import numpy as np

# Define which metrics make up the "Cost". 
# Assuming LOWER is ALWAYS BETTER for all these variables.
COST_METRICS = [
    "duration_s", 
    "pos_jitter_mm", 
    "ang_jitter_deg", 
    "reba_grand_right" # Change to left if the task is predominantly left-handed
]

def parse_params(trial: str) -> dict:
    """Extracts prototype features from the trial stem."""
    out = {"Length": None, "Size": None, "Weight": None, "Angle": None}
    tokens = trial.split("_")
    joined = "_".join(tokens)
    if "Not_weighted" in joined:
        out["Weight"] = "Not_weighted"
    elif "Front_weighted" in joined:
        out["Weight"] = "Front_weighted"
    for tok in tokens:
        if tok and tok.upper() == "A" and tok[1:].isdigit():
            out["Angle"] = int(tok[1:])
            break
    for tok in tokens:
        if tok in ("Long", "Short"):
            out["Length"] = tok
        elif tok in ("Large", "Small"):
            out["Size"] = tok
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--landmarks-root", type=Path, required=True, help="Path to Participant_Landmarks dir")
    args = ap.parse_args()

    metrics_dir = args.landmarks_root / "metrics"
    place_csv = metrics_dir / "place_metrics_combined.csv"
    posture_csv = metrics_dir / "posture_features_combined.csv"

    if not place_csv.is_file() or not posture_csv.is_file():
        sys.exit("Could not find both place and posture CSVs in the metrics directory.")

    # 1. Load Data
# 1. Load Data
    df_place = pd.read_csv(place_csv)
    df_posture = pd.read_csv(posture_csv)

    # 2. Merge on shared keys
    merge_keys = ['participant', 'trial', 'height']
    
    # NEW: Find any overlapping columns (like duration_s) and drop them from posture 
    # to prevent pandas from renaming them with _x and _y suffixes.
    overlapping = [c for c in df_posture.columns if c in df_place.columns and c not in merge_keys]
    df_posture = df_posture.drop(columns=overlapping)

    # Now merge safely
    df = pd.merge(df_place, df_posture, on=merge_keys, how='inner')

    # Ensure all required metrics exist in the merged dataframe
    missing_metrics = [m for m in COST_METRICS if m not in df.columns]
    if missing_metrics:
        sys.exit(f"Missing required metrics in merged data: {missing_metrics}")

    # 3. Parse Prototype Parameters
    params = df["trial"].apply(parse_params).apply(pd.Series)
    for c in ("Length", "Size", "Weight", "Angle"):
        df[c] = params[c]

    # 4. Standardize Data (Z-Scores)
    z_columns = []
    for metric in COST_METRICS:
        col_name = f"z_{metric}"
        z_columns.append(col_name)
        # Z = (X - Mean) / StdDev
        df[col_name] = (df[metric] - df[metric].mean()) / df[metric].std()

    # 5. Calculate Global Cost (Sum of Z-scores)
    # Because we assumed lower is better for all metrics, lower global cost = better.
    df["Global_Cost"] = df[z_columns].sum(axis=1)

    # 6. Aggregate by Prototype Configuration and Height
    group_keys = ["height", "Length", "Size", "Weight", "Angle"]
    
    # Calculate the mean of the Global Cost and the raw underlying metrics for context
    agg_dict = {"Global_Cost": "mean"}
    for m in COST_METRICS:
        agg_dict[m] = "mean"

    ranked = df.groupby(group_keys)[list(agg_dict.keys())].mean().reset_index()

    # Sort by height, then by lowest cost
    ranked = ranked.sort_values(by=["height", "Global_Cost"], ascending=[True, True])

    # 7. Extract and Print Winners
    out_file = metrics_dir / "prototype_rankings_by_height.csv"
    ranked.to_csv(out_file, index=False)

    print("\n" + "="*60)
    print("🏆 TOP PROTOTYPES BY HEIGHT (Lowest Global Cost) 🏆")
    print("="*60)

    for height in ["High", "Medium", "Low"]:
        height_data = ranked[ranked["height"] == height]
        if height_data.empty:
            continue
            
        top_3 = height_data.head(3)
        print(f"\n--- {height.upper()} TARGETS ---")
        
        for i, (_, row) in enumerate(top_3.iterrows(), 1):
            config = f"{row['Length']}, {row['Size']}, {row['Weight']}, Angle {row['Angle']}"
            print(f"#{i}: {config}")
            print(f"    Global Cost Score: {row['Global_Cost']:.2f}")
            print(f"    (Avg Duration: {row['duration_s']:.2f}s | Avg REBA: {row['reba_grand_right']:.2f})")

    print(f"\nFull ranked list saved to: {out_file}")

if __name__ == "__main__":
    main()